import random
import json
import time
import logging
from datetime import datetime
from faker import Faker
from kafka import KafkaProducer
from airflow import DAG
from airflow.operators.python import PythonOperator

default_args = {
    'owner': 'user',
    'start_date': datetime(2025, 1, 1),
    'retries': 1,
}

class DynamicDataCollectionAPI:
    def __init__(self, initial_users=5):
        """
        Initialize the API with a fixed number of users for streaming data.
        """
        self.users = []  # List of users
        self.fake = Faker()

        # Initialize with the given number of users
        for _ in range(initial_users):
            self.users.append(self.generate_random_user())

    def generate_random_user(self):
        """
        Generate a random user with associated location and weather information.
        """
        return {
            "user_id": f"u{random.randint(100, 999)}",
            "name": self.fake.name(),
            "email": self.fake.email(),
            "location": self.generate_random_location()
        }

    def generate_random_location(self):
        """
        Generate a random location with weather and nearby places.
        """
        return {
            "location_id": f"l{random.randint(100, 999)}",
            "name": self.fake.city(),
            "latitude": round(random.uniform(-90, 90), 6),
            "longitude": round(random.uniform(-180, 180), 6),
            "weather": self.generate_random_weather(),
            "nearby_places": self.generate_nearby_places()
        }

    def generate_random_weather(self):
        """
        Generate random weather conditions for a location.
        """
        weather_conditions = ["Clear", "Cloudy", "Rain", "Thunderstorms", "Snow", "Windy"]
        return {
            "temperature": round(random.uniform(-30, 50), 1),
            "conditions": random.choice(weather_conditions),
            "humidity": random.randint(0, 100),
            "wind_speed": round(random.uniform(0, 15), 1)
        }

    def generate_nearby_places(self):
        """
        Generate a list of nearby places within a location.
        """
        return [
            {
                "place_id": f"p{random.randint(1000, 9999)}",
                "name": self.fake.company(),
                "distance_km": round(random.uniform(0.5, 10), 2)
            }
            for _ in range(random.randint(2, 5))
        ]

    def get_users(self):
        """
        Return the current list of users.
        """
        return self.users


def stream_data():
    """
    Stream data generated by the DynamicDataCollectionAPI to Kafka.
    """
    # Set up logging
    logging.basicConfig(level=logging.INFO)

    # Create Kafka producer
    producer = KafkaProducer(bootstrap_servers=['broker:29092'], max_block_ms=5000)

    # Initialize the data generator
    data_generator = DynamicDataCollectionAPI(initial_users=5)

    # Stream data for a specified duration
    curr_time = time.time()
    while True:
        if time.time() > curr_time + 60:  # Run for 1 minute
            break
        try:
            # Fetch data
            users = data_generator.get_users()

            # Send the data to Kafka
            for user in users:
                producer.send('user_data', json.dumps(user).encode('utf-8'))
                logging.info(f"Data sent to Kafka: {user}")

            # Sleep to simulate real-time data streaming
            time.sleep(2)

        except Exception as e:
            # Log any exceptions
            logging.error(f"An error occurred: {e}")
            continue


# Define the Airflow DAG
with DAG('user_data_streaming',
         default_args=default_args,
         schedule='@daily',
         catchup=False) as dag:

    streaming_task = PythonOperator(
        task_id='stream_user_data',
        python_callable=stream_data
    )
